-- Jalankan seluruh SQL ini di Supabase > SQL Editor.
-- Database untuk aplikasi Manajemen Perkuliahan.

create table if not exists public.academic_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  date date not null,
  time time,
  category text not null check (category in ('kuliah','praktikum','tugas')),
  location text,
  note text,
  status text not null default 'belum' check (status in ('belum','selesai')),
  created_at timestamptz not null default now()
);

alter table public.academic_items enable row level security;

drop policy if exists "Users can view own academic items" on public.academic_items;
create policy "Users can view own academic items"
on public.academic_items for select
using (auth.uid() = user_id);

drop policy if exists "Users can insert own academic items" on public.academic_items;
create policy "Users can insert own academic items"
on public.academic_items for insert
with check (auth.uid() = user_id);

drop policy if exists "Users can update own academic items" on public.academic_items;
create policy "Users can update own academic items"
on public.academic_items for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own academic items" on public.academic_items;
create policy "Users can delete own academic items"
on public.academic_items for delete
using (auth.uid() = user_id);

create index if not exists academic_items_user_date_idx
on public.academic_items(user_id, date);